pub mod error;
pub mod types;
pub mod taxonomy;
pub mod manifest;
pub mod plugin;
pub mod context;
pub mod hook;
pub mod command;
pub mod surface;
pub mod capability;
pub mod store;
pub mod bus;
pub mod loader;
pub mod runtime;
pub mod dispatch;
pub mod render;

pub use error::{PluginError, LoadError, UpgradeError};
pub use types::{PluginId, SurfaceId, SubscriptionId, ContextId, Version};
pub use taxonomy::Taxonomy;
pub use manifest::Manifest;
pub use plugin::Plugin;
pub use context::{InitContext, RuntimeContext, UpgradeContext};
pub use hook::{HookSpec, HookTopic, Filter, FilterValue, HookMode, Delivery, BufferPolicy, DropPolicy, StreamEvent, EdgeEvent};
pub use command::{CommandInvocation, CommandName, CommandProvidedDecl};
pub use surface::{SurfaceDecl, SurfaceKind, SurfaceHandle, SurfaceEvent, Size, ResizePolicy};
pub use capability::{CapabilityDecl, CapabilityName, Scope, CapabilityGrant};
pub use store::{Store, StoreApi};
pub use bus::{Bus, BusMessage};
